[package]
name = "libp2p-chat-sample"
version = "0.1.0"
authors = ["jkcomment <jkcomment@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.26"
libp2p = "0.6.0"
env_logger = "0.6.0"
rand = "0.6"
tokio = "0.1"
tokio-stdin-stdout = "0.1"
void = "1.0"
